.github/workflows/main.yml, resources/scenario.yaml, workflow/Snakefile, workflow/envs/minimap2.yaml, workflow/envs/quast.yaml, workflow/envs/ragoo.yaml, workflow/report/assembly.rst, workflow/rules/assembly.smk, workflow/rules/common.smk, workflow/rules/read_mapping.smk, workflow/rules/ref.smk, workflow/rules/strain_calling.smk, workflow/rules/utils.smk, workflow/rules/variant_annotation.smk, workflow/rules/variant_calling.smk, workflow/rules/variant_filtration.smk, workflow/rules/variant_report.smk
- add raGOO (https://github.com/malonge/RaGOO) for the ordering of assembly contigs. Integrate output of raGOO into Pangolin.
- add Quast (http://quast.sourceforge.net/quast) for visualisation of config quality
=> raGOO & Quast

.tests/config/config.yaml, config/config.yaml, workflow/Snakefile, workflow/report/variant-calls.rst, workflow/rules/assembly.smk, workflow/rules/common.smk, workflow/rules/ref.smk, workflow/rules/utils.smk, workflow/rules/variant_annotation.smk, workflow/rules/variant_filtration.smk, workflow/rules/variant_report.smk
* Annotation needs to be obtained from Ensembl in order to be compatible with VEP.
* Add vembrane based configurable annotation filtering.
=> Fix annotation, add annotation based filtering

.gitattributes, .gitignore, .tests/config/config.yaml, .tests/config/pep/samples.csv, README.md, config/config.yaml, config/pep/samples.csv, preprocessing/update_sample_sheet.py, workflow/rules/common.smk
Script for 
- Updating the sample sheet with data from the incoming directory (with run id)
- Copying files into the data folder
- Moving files into the archive
=> Script for sample sheet update

workflow/envs/pangolin.yaml, workflow/envs/svn.yaml, workflow/rules/ref.smk, workflow/rules/strain_calling.smk
=> Pangolin fix

.tests/config/config.yaml, config/config.yaml, workflow/rules/common.smk, workflow/rules/strain_calling.smk, workflow/scripts/extract-strain-genomes.py
=> Use GISAID strain genomes in Kallisto

config/multiqc_config.yaml, workflow/rules/qc.smk
=> Add Picard and Kallisto to MultiQC

.github/workflows/main.yml
so it does not trigger on master
=> add if statement for canceling previous jobs

workflow/rules/strain_calling.smk
=> add subcategory for kallisto calls

.github/workflows/main.yml, workflow/report/ucsc.rst, workflow/report/variant-calls.rst, workflow/rules/common.smk, workflow/rules/generate_output.smk, workflow/rules/qc.smk, workflow/rules/read_mapping.smk, workflow/rules/read_trimming.smk, workflow/rules/variant_report.smk
=> provide vcfs for the ucsc genome browser

resources/report-table-formatter.js, workflow/rules/generate_output.smk, workflow/rules/ref.smk, workflow/scripts/generate_virologist_output.py
Reverts koesterlab/snakemake-workflow-sars-cov2#117
=> Revert "Integrate pangolin lineages into virologist report"

.github/workflows/main.yml, .tests/config/pep/samples.csv, workflow/rules/ref.smk
as they seem to hide some errors that were introduced recently.
=> disable caches

workflow/rules/benchmarking.smk, workflow/rules/generate_output.smk, workflow/rules/qc.smk
=> Log path fix

.tests/config/config.yaml, config/config.yaml, workflow/rules/benchmarking.smk, workflow/scripts/get-read-statistics.py
Overview of all reads length. Was interested in the 50% quantile for determining the number of reads to generate by mason.
=> Summarize length of all reads

workflow/scripts/extract-strains-from-gisaid-provision.py
create output folder (genome), if not exist
=> Fix extraction of genomes from GISAID

workflow/Snakefile, workflow/rules/benchmarking.smk, workflow/scripts/extract-strains-from-gisaid-provision.py, workflow/scripts/plot-pangolin-conflict.py
- Get correct share of PANGO calls for simulated samples based one reference sequence
- Get table of wrongly called lineages
=> Add statistics for pangolin calls synth samples with 1 strain

workflow/scripts/plot-lineages-over-time.py
=> Adjust lineages plot

.github/workflows/release-please.yml, .gitignore
<details><summary>Commit Structur</summary>
The commit message should be structured as follows:
```
```
- `BREAKING CHANGE:` a commit that has the text `BREAKING CHANGE`: at the beginning of its optional body or footer section introduces a breaking API change (correlating with `MAJOR` in semantic versioning). A breaking change can be part of commits of …
=> fix: release please indent

.github/workflows/release-please.yml
=> fix: change trigger of release please

.github/workflows/release-please.yml
Release-As: 0.1.0
```
```
- `BREAKING CHANGE:` a commit that has the text `BREAKING CHANGE`: at the beginning of its optional body or footer section introduces a breaking API change (correlating …
=> fix: release please step id

.github/workflows/release-please.yml
=> fix: release please pr tag

.github/workflows/release-please.yml
=> fix: release plase indent

.github/workflows/release-please.yml
=> fix: release please command

.github/workflows/release-please.yml
=> fix: release command

.github/workflows/release-please.yml
=> fix: release please if statement

.github/workflows/release-please.yml
=> fix: release please local PR checkout

.github/workflows/release-please.yml
=> fix: release please rmv double dollar

.github/workflows/publish-release.yaml
=> fix: change trigger of registry release action

.github/workflows/release-please.yml
=> fix: remove pre von release action

.github/workflows/release-please.yml
=> fix: release please if statement with release check

.github/workflows/release-please.yml
=> chore: add debug prints to release please action

.github/workflows/release-please.yml
=> refactor: release pr check

.github/workflows/release-please.yml
=> refactor: release please if statements

.github/workflows/release-please.yml
=> refactor: release condition

.github/workflows/release-please.yml
=> refactor: release if statement - change " to '

.github/workflows/release-please.yml
=> fix: add GISAID var to env

.github/workflows/release-please.yml
=> fix: change path of docker file for release creation

.github/workflows/release-please.yml
=> fix: maximize build space for container image

.github/workflows/release-please.yml
=> fix: rmv path for buildah

.github/workflows/release-please.yml
=> fix: change to docker/build-push-action action for release containers

.github/workflows/main.yml, workflow/Snakefile, workflow/rules/generate_output.smk, workflow/rules/qc.smk, workflow/rules/read_trimming.smk
=> fix: update linting

README.md
=> fix: update readme to trigger release

.github/workflows/release-please.yml
=> fix: add log in to quay registry

workflow/envs/pangolin.yaml
=> fix: specify snakemake version used in pangolin env

.github/workflows/copyright-preamble.yml
=> ci: add newline to preamble action

.github/workflows/copyright-preamble.yml
=> ci: update copyright action

.github/workflows/copyright-preamble.yml
=> ci: update paths of copyright preamble

.github/workflows/main.yml
=> ci: remove double newline in simulated gisaid data

config/config.yaml
=> fix: typo in config.yaml

config/config.yaml
add all current voc mutations based on rki mention and remove duplication
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/DESH/Bericht_VOC_2021-07-14.pdf?__blob=publicationFile
=> feat: add more voc mutations to config

.snakemake-workflow-catalog.yml
=> build(workflow catalog): don't create another report

workflow/schemas/config.schema.yaml, workflow/schemas/samples.schema.yaml
1. changed JSON schema validator in files ./schemas/config.schema.yaml and ./schemas/samples.schema.yaml from "http://json-schema.org/draft-06/schema#" to "https://json-schema.org/draft/2020-12/schema"
2. added missing properties from config.yaml to config.schema.yaml:
- lineage-references
- voc
3. deleted items in config.schema.yaml that were missing in config.yaml:
- use-kallisto
4. rearranged item order of extracted-strain-genomes and use-gisaid according to the order in config.yaml for better readability
#326
=> fix: changed JSON schema validator and updated files

.github/dependabot.yml
Changes prefix of Dependa bots update PRs from `ci`to `chore(ci)`
None
- **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
- **test**: Adding missing tests or correcting existing tests
=> ci: change prefix of dependabots PRs

.github/pull_request_template.md
- **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
- **test**: Adding missing tests or correcting existing tests
=> chore(pr_template): update checklist and hide type of changes

.gitignore
I often aggregate different samples in many sample sheets when testing a feature. 
This results in this rather annoying tracking of these sheets:
Changes gitignore, so that not all other sample sheets in the pep folder are covered by git version tracking.
- **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing …
=> chore(gitignore): only track version of config.yaml and samples.csv

.github/pull_request_template.md
Fix double space in pr template
=> ci: fix typo in pr template

.github/workflows/copyright-preamble.yml
... to fit conventional commits format
=> ci: adjust commit message of copyright-preamble.yml 

docs/consumer-guide/faqs.md, docs/consumer-guide/first-impression.md, docs/consumer-guide/index.md, docs/consumer-guide/lineages-and-variants.md, docs/consumer-guide/report-structure.md, docs/consumer-guide/submission-ready-genomes.md, mkdocs.yml
Add consumer guide section.
None
=> docs: add consumer guide

.github/workflows/main.yml
The formatting action also runs on release PRs. However, the automatic changelog is not correctly formatted. When formatting, the changelog is now ignored. 
None
=> ci: ignore changelog when formatting

.github/workflows/documentation.yml, mkdocs.yml
Changed the order the tabs in the about navigation to team -> license -> changelog, as the changelog is a huge file and it's toc displaces the license
=> docs: change order of release notes nav

mkdocs.yml
Add missing consumer guide index
None
=> docs: add missing consumer guide index

workflow/rules/common.smk, workflow/rules/generate_output.smk
The sequencing technology list handed to the `generate-high-quality-report.py` was not filtered. Thus, the sample list and the technology list could differ and the construction of the DataFrame would fail.
This PR introduces a filtered technology list to fix this problem.
=> fix: generation of high quality genomes

.github/workflows/main.yml, .pre-commit-config.yaml, .tests/config/multiqc_config.yaml, CONTRIBUTING.md, config/multiqc_config.yaml
Currently, everything is excluded, due to a training pipe.
None
[structure of the conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/).
`black workflow/` if needed.
[`CONTRIBUTING.md`]:(https://github.com/IKIM-Essen/uncovar/blob/master/CONTRIBUTING.md)
=> fix: rmv pipe from pre-commit

.github/pull_request_template.md, .pre-commit-config.yaml
adds pointer in PR template to pre-commit  
None
[structure of the conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/).
`black workflow/` if needed.
[`CONTRIBUTING.md`]:(https://github.com/IKIM-Essen/uncovar/blob/master/CONTRIBUTING.md)
=> ci: update PR template with pre-commit pointer

docs/consumer-guide/report-structure.md, workflow/rules/generate_output.smk
Uniform report name
Fixed typo in docs
=> fix: name fixes

workflow/envs/bamclipper.yaml, workflow/rules/common.smk, workflow/rules/generate_output.smk
some fixes, that arouse from production
None
=> fix: pangolin input for overview table, bamclipper samtools error, include flag for high quality genome report

workflow/envs/varlociraptor.yaml
This should yield even better results: https://github.com/varlociraptor/varlociraptor/releases/tag/v4.9.0
=> feat: update to varlociraptor 4.9

resources/report-table-formatter.js
The Mutations columns are not formatted, because the column names changed.
=> fix: update the mutations columns in the overview table formatter

workflow/scripts/plot-lineages-over-time.py
=> fix: correct filtering in df

workflow/envs/rbt.yaml
This should fix the popovers in the overview table, as soon as rbt 0.38.2 comes available.
=> fix: bump rust-bio-tools to 0.38

.github/workflows/main.yml, .github/workflows/release-please.yml
The release please action was updated and outputs now a JSON object instead of a PR number.
This PR adds support to parse the JSON object and extract the PR number.
N/A
=> fix(ci): parse new json output from release please

workflow/rules/variant_report.smk
fix bug where the fasta index of the reference genome was not found
=> fix: add index for vcf report

workflow/rules/long_read.smk
Adds stdout redirects for logging.
N/A
=> fix: canu and porechop porechop

.github/workflows/release-please.yml
Due to the updated release please version, the PR branch named changed to `release-please--branches--master`. Changed the Action accordingly.
N/A
=> fix(ci): change release please PR branch

workflow/rules/read_mapping.smk
Removing the temp flag from main recalibrated alignment file
=> fix: untemp recalibrated bam

README.md
Removal of author list in the readme, as the number of contributors to the workflow is increasing.
N/A
=> docs(readme): remove author list

workflow/envs/rbt.yaml
hard code newest version of rbt to easily fix all used branches
=> feat: update rbt to 0.39

workflow/notebooks/plot-all-strains-pangolin.py.ipynb, workflow/scripts/aggregate-pangolin-calls-per-stage.py, workflow/scripts/evaluate-strain-call-error.py, workflow/scripts/summarize-non-cov2.py
=> fix: change status to qc_status

resources/lineage-variant-table-formatter.js, workflow/scripts/generate-lineage-variant-table.py
with using the product of probabilities the overall probability of events was artificially increased. Therefore the calculation was switched to the minimum. Furthermore the Color scale in the final output was adjusted
=> fix: voc probability

.github/workflows/main.yml, resources/lineage-variant-table-formatter.js, workflow/envs/pangolin.yaml, workflow/rules/read_clipping.smk, workflow/scripts/bed-to-tsv.py, workflow/scripts/collect_lineage_calls.py, workflow/scripts/evaluate-strain-call-error.py, workflow/scripts/extract-strains-from-gisaid-provision.py, workflow/scripts/generate-lineage-variant-table.py, workflow/scripts/generate-overview-table.py, workflow/scripts/plot-all-coverage.py, workflow/scripts/plot-assembly-comparison.py, workflow/scripts/plot-dependency-of-pangolin-call.py, workflow/scripts/plot-pangolin-conflict.py, workflow/scripts/plot-primer-clipping.py
Merge changes from master in branch
https://github.com/IKIM-Essen/uncovar/issues/537
=> refactor: merge master in branch

.github/workflows/main.yml
Due to failing test rules, Nanopore actions are disabled until the version update is fixed properly as ONT branch is currently not in regular use
=> fix: disable ont actions

workflow/rules/read_clipping.smk, workflow/scripts/bed-to-bedpe.py, workflow/scripts/plot-primer-clipping.py
Reverts IKIM-Essen/uncovar#545
=> fix: Revert "refactor: fgbio read clipping"

workflow/envs/kraken.yaml, workflow/rules/ref.smk
=> fix: kraken db

workflow/Snakefile, workflow/rules/common.smk
=> refactor: work around bug in snakefmt that adds two lines after each include by moving an if statement into common.smk

workflow/envs/pangolin.yaml
=> build: update pangolin to version 4.3

README.md
=> feat: Update README.md for dark/light theme

workflow/scripts/masking.py, workflow/scripts/quality-filter.py
with Nanopore samples, the pipeline was not capable of producing QA compliant reads.
=> fix: QA genome generation

.github/workflows/main.yml, workflow/scripts/collect-lineage-variants.py
=> fix: update link for covariants

workflow/rules/common.smk
=> fix: zipped fastqs for kraken

.github/workflows/main.yml, workflow/rules/ref.smk
=> fix: pipe of stdout

workflow/envs/varlociraptor.yaml
=> fix: pin to varlociraptor 8.4.4

workflow/scripts/generate-overview-table.py
=> fix: calculation in overview table

workflow/rules/read_mapping.smk
=> refactor: update wrappers

workflow/rules/long_read.smk
=> fix: ont primer clipping

.github/workflows/copyright-preamble.yml
=> fix: exclude files from auto copyright action

README.md
=> refactor: update README.md with GitHub pages link

workflow/rules/qc.smk
Change the input for Kraken analysis (rule species_diversity_before_se)
=> fix: changed kraken input files for ont

workflow/rules/ref.smk, workflow/rules/strain_calling.smk
=> fix: pangolin data updates
