IKIM-Essen/uncovar

- resources/custom-table-report.js
- workflow/envs/rbt.yaml
This PR updates `rust-bio-tools` to version `0.19.1`. This should fix missing linkouts in the sidebar of the table-report. It also fixes some empty lines in the dropdown menu discovered and fixed by @FelixMoelder.
> Update rust-bio-tools version

- workflow/envs/pangolin.yaml
- workflow/rules/strain_calling.smk
This PR introduces rule, which should update pangolin every run by executing `pangolin --update`.
It could be considered to remove the version number in the yaml environment to always use the latest pangolin version. However, this would of course speak against a reproducible result of the workflow.
> Pangolin update rule

- config/config.yaml
- workflow/Snakefile
- workflow/rules/common.smk
Closes #61 
I've decided to use expand + a function instead of a wildcard to save the latest run results. This approach shouldn't overwrite results from older runs if something upstream changes. 
However, I somehow don't like the "style" to get an output of the all rule to save the results. Maybe checkpoints would be another option. If someone has an idea to realise the archiving of the results better, please feel free to contribute.
> save results rule

- workflow/rules/read_mapping.smk
They are important to check if any problems occur.
> do not mark recalibrated read alignments as temporary

- .github/workflows/main.yml
- .tests/config/config.yaml
- .tests/config/pep/samples.csv
- config/config.yaml
- config/pep/samples.csv
- workflow/Snakefile
- workflow/envs/varlociraptor.yaml
- workflow/rules/common.smk
- workflow/rules/read_mapping.smk
- workflow/rules/read_trimming.smk
- workflow/rules/variant_calling.smk
It is now possible to define that a sample is amplicon data. In that case, valrociraptor will omit bias estimation and PCR deduplication is skipped.
> Allow to configure the workflow for amplicon data

- .github/workflows/main.yml
This PR adds the log files from CI runs to the uploaded artifacts. This may be quite helpful for debugging.
> Upload logs as artifacts

- workflow/envs/rbt.yaml
@mbargull, do you have an idea why we need to do this? Seems like rbt was built on top of mkl, but on some systems a different (non-mkl) variant of openmp is chosen?
> Workaround: explicitly add mkl as a dependency to the rbt env

- workflow/scripts/generate_virologist_output.py
We loose the histogram plotting ability in the HTML table then. Instead, we can add additional fancy int formatting in the table renderer.
> do not format numbers as strings in qc table

- .github/workflows/main.yml
Just a quick fix to #137 which downloaded the GitHub html instead of the actual reads.
> Fix downloading B117 reads

- workflow/envs/rbt.yaml
- workflow/rules/generate_output.smk
This PR pins the sample column of the qc report so that is always visible for the user. We need to have https://github.com/rust-bio/rust-bio-tools/pull/147 merged and released in order for this to work properly.
> Pin sample column of qc report

- .github/pull_request_template.md
> docs: simplify pr template

- .github/workflows/main.yml
- workflow/envs/multiqc.yaml
- workflow/envs/snakemake.yaml
- workflow/notebooks/call-strains.py.ipynb
- workflow/rules/qc.smk
> build: temporarily change MultiQC wrapper to env rule

- workflow/rules/qc.smk
- workflow/scripts/extract-reads-of-interest.py
Add index to rule `extract_reads_of_interest`. This removes the following message:
```python
[E::idx_find_and_load] Could not retrieve index file for 'results/{date}/mapped/ref~main+human/{sample}.bam'
```
- **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
- **test**: Adding missing tests …
> fix: add bam index for extract_reads_of_interest

- workflow/rules/long_read.smk
- workflow/scripts/extract-strains-from-gisaid-provision.py
Currently, there is a file in GISAID EpiCoV DataBase which is called `B.1.1.529 (probably).fasta` (omicron). This file causes downstream problems when casting all lineage genomes together, due to the spaces and parenthesis.  
This PR removes lineage, that contains parenthesis in the name from extraction.
> fix: GISAID lineage extraction [B.1.1.529 (probably).fasta]

- .github/workflows/main.yml
GitHub Action runners disk are overflowing. Disabling caching could lead to lesser disk space but to longer ci testing times.
[structure of the conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/).
`black workflow/` if needed.
[`CONTRIBUTING.md`]:(https://github.com/IKIM-Essen/uncovar/blob/master/CONTRIBUTING.md)
> ci: disable cache

- resources/report-table-formatter.js
After renaming columns of the overview table, the names in the formatter were not changed
> fix: rename column

- resources/report-table-formatter.js
The overview table is still broken. This PR resets the formatted to an older version (3af43b991af218931996d9093ecf944bff907476)
> fix: reset overview table formatter to older version

- workflow/rules/common.smk
There was a problem with the include_flag in common.smk. The get_assemblies_for_submission function gives the path to the faster file, not the name, leading to a KeyError in get_include_flag. This causes the inclusion of files in the high-quality-genomes, that should be excluded. Problem fixed by changing the functions used in get_include_flag_for_date and taking into account the lengths of the lists from get_assemblies_for_submission and get_sample_for_date.
> fix: fixed include flag KeyError

- .github/workflows/release-please.yml
Added stdout redirect of release please output. Currently, the if statement tries to interpret the release please output as a command.
N/A
> fix(ci): add missing missing echo to release please

- workflow/notebooks/plot-all-strains-pangolin.py.ipynb
In the aggregation plot of all pangolin calls, samples were only included if they had a value for scorpio support. To fix that the value was excluded from the plotting script
> fix: pangolin plot

- .github/workflows/main.yml
- workflow/envs/snakemake.yaml
The download of `NC_000021.9` fails, because of an internal sever error over at ncbi:
```bash
...
CCCTCTCCCTCACTCTTATAAGGACACTTAAGATTGCATTTAGAGCCCACCAAGATAATTCATGATAATC
TTCCATCACAAAATTCTTCACTTATTCACATCTGCAAGTCTCTTTGCCATAAAGGTTACATTTACAGGTA
CTAAGGATTAAGACCTGACATCTCTTGAGGCCATTATTCACCCTAACACA<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
<head>
<title>NCBI/ffsrv12 - WWW Error 500 Diagnostic</title>
<style type="text/css">
h1.error {color: red; font-size: 40pt}
div.diags {text-indent: 0.5in }
</style>
</head>
<body>
<h1>Server Error</h1>
<p>Your request could not be processed due to a problem on
our Web server.  This could be a transient problem, please
try the query again.  If it doesn't clear up within a
reasonable period of time, …
```
> fix(ci): change human reference from NC_000021.9 to BA000005.3

- .tests/config/config.yaml
- config/config.yaml
- workflow/rules/generate_output.smk
- workflow/scripts/generate-high-quality-report.py
- added a new parameter _sending_lab_number_ to the config file in order to make the sending lab column in RKI report csv adjustable
- the date of the current run is now also used to refill the column DATE_DRAW in RKI report csv
https://github.com/IKIM-Essen/uncovar/issues/334
- [ x] I've formatted the PR title in accordance with the [structure of the conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/).
- [ x] I've updated the code style using [`pre-commit`](https://ikim-essen.github.io/uncovar/dev-guide/contributing/#pre-commit) if needed.
- [ x] I've read the [`CODE_OF_CONDUCT.md`] document.
- [ x] I've read the [`CONTRIBUTING.md`] guide.
[`CONTRIBUTING.md`]: …
> feat: make sending lab column in rki report csv adjustable via config file

- resources/lineage-variant-table-formatter.js
- workflow/scripts/generate-lineage-variant-table.py
refactor VOC mutation table generation, Fix Jaccard coefficient, remove top 5 list, cleanup
> fix: refactor VOC mutation table generation

- workflow/rules/common.smk
This PR  adds a nofilter flag for variant calls. This flag was already prepared (see wildcards-constrains), but never used. This PR is needed for the benchmarking.
N/A
> fix: add nofilter flag for variant calls

- workflow/rules/read_clipping.smk
When clipping amplicon primers with the bamclipper tool, primers not exactly matching the defined region from the primer.bed file aren't clipped properly. Therefore additional up and downstream positions are added. Maybe this should be done via the config in the future instead of hard coding the numbers
> fix: primer clipping add up- and downstream

- .github/workflows/main.yml
- .pre-commit-config.yaml
- workflow/envs/trinity.yaml
- workflow/rules/benchmarking.smk
- workflow/scripts/evaluate-strain-call-error.py
Updates black to rev 22.3.0.
Should fix 
```
ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/.cache/pre-commit/repoykquj97p/py_env-python3.10/lib/python3.10/site-packages/click/__init__.py)
```
See https://github.com/psf/black/issues/2964#issuecomment-1080974737
N/A
> fix(ci): update black to rev 22.3.0

- workflow/rules/common.smk
pd.read_csv(f, squeeze=True) is deprecated and replaced with .squeeze("columns")
#530 
> fix: squeeze

- config/pep/samples.csv
- workflow/scripts/collect_lineage_calls.py
- workflow/scripts/evaluate-strain-call-error.py
- workflow/scripts/extract-strains-from-gisaid-provision.py
- workflow/scripts/generate-lineage-variant-table.py
- workflow/scripts/generate-overview-table.py
- workflow/scripts/plot-all-coverage.py
- workflow/scripts/plot-assembly-comparison.py
- workflow/scripts/plot-dependency-of-pangolin-call.py
- workflow/scripts/plot-pangolin-conflict.py
- workflow/scripts/plot-primer-clipping.py
fix: df.append is outdated and replaced by pd.concat
#496 
> fix: Replace outdated df append

- workflow/envs/varlociraptor.yaml
- workflow/rules/common.smk
> fix: use latest varlociraptor release and ignore all biases in case of known lineage variant calling

- workflow/rules/common.smk
Changed the path fetching in common.smk -> get_resource(). Should fetch the total link if snake deploy is used so files can be used from the resources folder in the repository.
> fix: changes in path requirements for snakedeploy

- workflow/Snakefile
- workflow/envs/varlociraptor.yaml
- workflow/rules/assembly.smk
- workflow/rules/common.smk
- workflow/rules/variant_filtration.smk
Important: 
Before, we used only clonal variants (VAF=100%) for assembly polishing. This PR changes this behavior to also use major subclonal variants to polish the assembly (VAF>=50%). This is open for discussion. My idea is: the assembly should represent the major subclone in the sample (if there are multiple ones). If we only use clonal variants like before, the assembly could contain individual loci where the majority of the reads disagree with the assembly. This is not what we would want I think, since it also hampers the predictions of pangolin.
> fix: improved clonality event definition, usage of major subclone for assembly polishing; upgrade to varlociraptor 6.0

- workflow/rules/common.smk
- workflow/rules/variant_calling.smk
nanopore suffers from homopolymer errors. Varlociraptor can deal with them by having additional states in its pairHMM used for realignment of reads against considered alleles. This mode has to be explicitly activated whenever we process a nanopore sample.
> fix: use homopolymer-pair-HMM-mode of Varlociraptor in case of nanopore reads

- .github/workflows/main.yml
- workflow/rules/common.smk
- workflow/rules/qc.smk
> fix: update multiqc

- .github/workflows/main.yml
after the docker container in the Snakemake github action is updated to Snakemake version 8.0.1, the `-r` flag is discontinued
> fix: remove -r flag

- workflow/rules/generate_output.smk
Reverts IKIM-Essen/uncovar#637
> fix: Revert "remove Snakemake environment from report rule"

- .github/workflows/main.yml
- workflow/envs/pangolin.yaml
- workflow/envs/spades.yaml
> chore: checkout full history for formatting

- workflow/rules/read_clipping.smk
Currently log cannot be found by the system and workflow fails. Removing the cwd parameter from the path of the log fixes it.
> fix: fix log not being found by the system

- workflow/rules/assembly.smk
Usage of relative paths leads to files not being found on shared filesystem storage systems. The shell command is fixed to use the output directory of the tool without cd'ing to the folder and needing to use relative paths.
> fix: fix file not found error on shared fs storage
